---
version: 2
# command define
commands:
  - title: Reload
    command: :reload-config

  - title: Editor
    os: windows
    command: notepad
    arguments:
      - "${INPUT}"
  - title: Editor
    os: linux
    command: gedit
    arguments:
      - ${INPUT}
  - title: Editor
    os: mac
    command: open
    arguments:
      - '-e'
      - ${INPUT}

  - title: Explorer
    os: windows
    command: explorer
    arguments:
      - '/select,"${INPUT}"'
  - title: Explorer
    os: mac
    command: open
    arguments:
      - '-R'
      - ${INPUT}

# linter,formatter setting
tools:
  cppcheck-lint: &cppcheck-lint
    lint-command: 'cppcheck --enable=style --error-exitcode=1 ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: %m'

  vale-lint: &vale-lint
    lint-command: 'vale --relative --output line ${INPUT}'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c:%*[^:]:%m'

  vint-lint: &vint-lint
    lint-command: 'vint --stdin-display-name ${INPUT} -'
    lint-stdin: true

  nvcheck-lint: &nvcheck-lint
    lint-command: 'nvcheck ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l: %m'

  nvcheck-format: &nvcheck-format
    format-command: 'nvcheck -r ${INPUT}'

  markdownlint-lint: &markdownlint-lint
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'
      - '%f: %l: %m'

  markdownlint-format: &markdownlint-format
    format-command: 'markdownlint -f ${INPUT}'

  jq-format: &jq-format
    format-command: 'jq .'

  fixjson-format: &fixjson-format
    format-command: 'fixjson'

  shellcheck-lint: &shellcheck-lint
    lint-command: 'shellcheck -s bash -f gcc -x -o all -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  shfmt-format: &shfmt-format
    format-command: 'shfmt -ln bash -kp'

  flake8-lint: &flake8-lint
    lint-command: 'flake8 --stdin-display-name ${INPUT} -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m'

  mypy-lint: &mypy-lint
    lint-command: 'mypy --show-column-numbers'
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

  yamllint-lint: &yamllint-lint
    lint-command: 'yamllint --strict --format parsable ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: [%trror] %m'
      - '%f:%l:%c: [%tarning] %m'
    env:
      - 'PYTHONIOENCODING=UTF-8'

  restructuredtext-lint-lint: &restructuredtext-lint-lint
    lint-command: 'restructuredtext-lint --encoding utf-8 --level warning --format text ${INPUT}'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%tARNING %f:%l %m'
      - '%tRROR %f:%l %m'

  eslint-lint: &eslint-lint
    lint-command: 'npx --no-install eslint -f unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true

  eslint-format: &eslint-format
    lint-command: 'npx --no-install eslint --fix ${INPUT}'

  stylelint-lint: &stylelint-lint
    lint-command: 'npx --no-install stylelint --formatter unix --stdin --stdin-filename ${INPUT}'
    lint-ignore-exit-code: false
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %m [%trror]'
      - '%f:%l:%c: %m [%tarning]'

  excitetranslate-hover: &excitetranslate-hover
    hover-command: 'excitetranslate'
    hover-stdin: true

# languages setting
languages:
  vim:
    - <<: *vint-lint

  markdown:
    - <<: *markdownlint-lint
    - <<: *markdownlint-format
    - <<: *vale-lint
    - <<: *nvcheck-lint
    - <<: *nvcheck-format

  json:
    - <<: *jq-format
    - <<: *fixjson-format

  json5:
    - <<: *fixjson-format

  text:
    - <<: *vale-lint
    - <<: *nvcheck-lint
    - <<: *nvcheck-format

  help:
    - <<: *vale-lint
    - <<: *nvcheck-lint
    - <<: *nvcheck-format

  cpp:
    - <<: *cppcheck-lint

  c:
    - <<: *cppcheck-lint

  sh:
    - <<: *shellcheck-lint
    - <<: *shfmt-format

  yaml:
    - <<: *yamllint-lint

  rst:
    - <<: *restructuredtext-lint-lint
    - <<: *vale-lint
    - <<: *nvcheck-lint
    - <<: *nvcheck-format

  javascript:
    - <<: *eslint-lint
    - <<: *eslint-format

  typescript:
    - <<: *eslint-lint
    - <<: *eslint-format

  css:
    - <<: *stylelint-lint

  scss:
    - <<: *stylelint-lint

  sass:
    - <<: *stylelint-lint

  less:
    - <<: *stylelint-lint

  sugarss:
    - <<: *stylelint-lint

  python:
    - <<: *flake8-lint
    - <<: *mypy-lint

  _:
    - <<: *excitetranslate-hover
...
