languages:
  vim:
    lint-command: 'vint -'
    lint-stdin: true

  markdown:
    lint-command: 'markdownlint -s'
    lint-stdin: true
    lint-formats:
      - '%f:%l %m'

  json:
    format-command: 'jq .'
    lint-stdin: true
    lint-ignore-exit-code: true

  text:
    lint-command: 'vale --relative --output line ${INPUT}'
    lint-stdin: false
    lint-ignore-exit-code: true
    lint-formats:
      - '%f:%l:%c:%*[^:]:%m'

  cpp:
    lint-command: 'cppcheck --enable=style --error-exitcode=1 ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: %m'
  c:
    lint-command: 'cppcheck --enable=style --error-exitcode=1 ${INPUT}'
    lint-stdin: false
    lint-formats:
      - '%f:%l:%c: %m'

  sh:
    lint-command: 'shellcheck -s bash -f gcc -x -o all -'
    lint-stdin: true
    lint-formats:
      - '%f:%l:%c: %trror: %m'
      - '%f:%l:%c: %tarning: %m'
      - '%f:%l:%c: %tote: %m'

